version: 2
registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{secrets.READER_TOKEN}}

updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: "monday"
      time: "08:00"
      timezone: "Europe/Oslo"
    labels:
      - "dependencies"
      - "github-actions"

  - package-ecosystem: npm
    directory: "/client"
    schedule:
      interval: weekly
      day: "monday"
      time: "08:00"
      timezone: "Europe/Oslo"
    labels:
      - "dependencies"
      - "client"
    groups:
      "@navikt*":
        patterns:
          - "@navikt/*"
      "@testing-library*":
        patterns:
          - "@testing-library/*"
      "react*":
        patterns:
          - "react"
          - "react-dom"
          - "react-router-dom"
          - "react-scripts"
      "typescript*":
        patterns:
          - "typescript"
          - "ts-node"
          - "ts-jest"
          - "@typescript-eslint/*"
      "jest*":
        patterns:
          - "jest"
          - "jest-*"
          - "@types/jest"
          - "babel-jest"
      "vite*":
        patterns:
          - "vite"
          - "@vitejs/*"
      "eslint*":
        patterns:
          - "eslint-plugin-*"
      "babel*":
        patterns:
          - "@babel/*"
          - "babel-*"
      "highcharts*":
        patterns:
          - "highcharts"
          - "highcharts-react-official"
    cooldown:
      default-days: 7
      exclude:
        - "@navikt*"
      applies-to: version-updates
    registries:
      - npm-github

  - package-ecosystem: npm
    directory: "/server"
    schedule:
      interval: weekly
      day: "monday"
      time: "08:00"
      timezone: "Europe/Oslo"
    labels:
      - "dependencies"
      - "server"
    groups:
      "typescript*":
        patterns:
          - "typescript"
          - "ts-node"
          - "@typescript-eslint/*"
      "jest*":
        patterns:
          - "jest"
          - "@types/jest"
          - "babel-jest"
      "babel*":
        patterns:
          - "@babel/*"
          - "babel-*"
      "express*":
        patterns:
          - "express"
          - "express-session"
          - "@types/express"
          - "@types/express-session"
    cooldown:
      default-days: 7
      applies-to: version-updates
    registries:
      - npm-github

  - package-ecosystem: docker
    directory: "/client"
    schedule:
      interval: weekly
      day: "monday"
      time: "08:00"
      timezone: "Europe/Oslo"
    labels:
      - "dependencies"
      - "docker"
      - "client"

  - package-ecosystem: docker
    directory: "/server"
    schedule:
      interval: weekly
      day: "monday"
      time: "08:00"
      timezone: "Europe/Oslo"
    labels:
      - "dependencies"
      - "docker"
      - "server"
